name: 'PR'

on:
  pull_request:
    branches: [ 'main' ]

defaults:
  run:
    shell: PowerShell

permissions: read-all

jobs:
  PR:
    runs-on: [ windows-latest ]
    steps:
      - name: Chill
        run: |
          Start-Sleep -seconds 1